language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

install:
  - $PIP install .

script:
  - cd tests
  - mkdir wheelhouse
  - autowheel $TRAVIS_OS_NAME --output-dir=wheelhouse
  - ls wheelhouse
