language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
           PLATFORM=linux32
    - sudo: required
      services:
        - docker
      env: PIP=pip
           PLATFORM=linux64
    - os: osx
      language: generic
      env: PIP=pip2
           PLATFORM=macosx

install:
  - $PIP install .

script:
  - python setup.py check --restructuredtext
  - cd tests
  - mkdir wheelhouse
  - autowheel $PLATFORM --output-dir=wheelhouse --build-existing
  - ls wheelhouse
