language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

install:
  - python setup.py develop

script:
  - cd tests
  - mkdir wheelhouse
  - autowheeel $TRAVIS_OS_NAME wheelhouse
  - ls wheelhouse
