install:
  - pip install .

build_script:
  - cd tests
  - mkdir wheelhouse
  - autowheel windows32 --output-dir=wheelhouse --no-ignore-existing
  - autowheel windows64 --output-dir=wheelhouse --no-ignore-existing
  - dir wheelhouse

artifacts:
  - path: "tests\\wheelhouse\\*.whl"
    name: Wheels
